yarnPath: '.yarn/releases/yarn-berry.cjs'
pnpMode: loose
packageExtensions:
  '@chakra-ui/checkbox@*':
    dependencies:
      framer-motion: '^3.0.0'
      react-dom: '^17.0.0'
  '@chakra-ui/portal@*':
    dependencies:
      react-dom: '^17.0.0'
  '@chakra-ui/radio@*':
    dependencies:
      react-dom: '^17.0.0'
  '@chakra-ui/toast@*':
    dependencies:
      react-dom: '^17.0.0'
  '@chakra-ui/transition@*':
    dependencies:
      framer-motion: '^3.0.0'
  '@chakra-ui/system@*':
    dependencies:
      '@emotion/react': '^11.0.0'
      '@emotion/styled': '^11.0.0'
  '@chakra-ui/utils@*':
    dependencies:
      react: '^17.0.0'

  '@reach/visually-hidden@*':
    dependencies:
      prop-types: '^15.0.0'

  'react-twitter-widgets@*':
    dependencies:
      '@babel/runtime': '*'
