packageExtensions:
  '@chakra-ui/checkbox@*':
    dependencies:
      framer-motion: '*'
      react-dom: '*'
  '@chakra-ui/portal@*':
    dependencies:
      react-dom: '*'
  '@chakra-ui/radio@*':
    dependencies:
      react-dom: '*'
  '@chakra-ui/system@*':
    dependencies:
      '@emotion/react': '*'
      '@emotion/styled': '*'
  '@chakra-ui/toast@*':
    dependencies:
      react-dom: '*'
  '@chakra-ui/transition@*':
    dependencies:
      framer-motion: '*'
  '@chakra-ui/utils@*':
    dependencies:
      react: '*'
  '@reach/visually-hidden@*':
    dependencies:
      prop-types: '*'
  eslint@*:
    dependencies:
      supports-color: '*'
  react-twitter-widgets@*:
    dependencies:
      '@babel/runtime': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

pnpMode: loose
# yarnPath: .yarn/releases/yarn-berry.cjs
