version: '3'

services:
  redis:
    container_name: redis-alpine
    image: redis:6
    restart: always
    ports:
      - 6379:6379
    networks:
      - devtools

  postgresql:
    container_name: postgres
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=datatorch
    networks:
      - devtools
    volumes:
      - ~/volumes/postgres/data:/var/lib/postgresql/data

networks:
  devtools:
    driver: bridge
