mutation createArticlePost($articleDraftID: String!, $publication: String! $postType: ArticlePostType) {
  createArticlePost(articleDraftId:$articleDraftID, publication:$publication, postType: $postType){
    id
    publication
    postType
  }
}

mutation createChildArticlePost($articleDraftID: String!, $publication: String! $postType: ArticlePostType $parentId: String) {
  createChildArticlePost(articleDraftId:$articleDraftID, publication:$publication, postType: $postType, parentId: $parentId){
    id
    publication
    postType
    childOf {
      id
    }
  }
}

mutation deleteArticlePost($articlePostId: String!) {
  deleteArticlePost(articlePostId:$articlePostId){
    id
  }
}

query getArticlePostsByPublication($publicationName: String! $postType: ArticlePostType){
  getArticlePostsByPublication(publicationName:$publicationName postType:$postType) {
    id
    publication
    postType
    articleDraft {
      id
      author {
        name
      }
      title
      content
    }
  }
}

query getCommentsForPostId($postId: String!){
  getChildrenArticlePostsForPostId(postId:$postId postType:COMMENT) {
    id
    publication
    postType
    articleDraft {
      id
      author {
        name
      }
      title
      content
    }
  }
}

query getArticlePostById($articlePostId: String!) {
    getArticlePostById(articlePostId:$articlePostId) {
      id
      publication
      postType
      articleDraft {
        id
        author {
          name
        }
        title
        content
      }
    }
}

# query getArticleDraftByAuthorId($authorId: String!) {
#   getArticleDrafts(projectOwnerId:$authorId){
#     id
#     title
#     createdAt
#   }
# }

# query getLastArticleDraft($authorId: String!) {
#   getLastArticleDraft(projectOwnerId:$authorId){
#     id
#     author {
#       id
#     }
#     title
#     createdAt
#   }
# }