name: datatorch-cli
summary: CLI for Datatorch 
description: |
      CLI for Datatouch Platform and CLI allowing developers to progromaticly use The Datatorch Platform in the CI/CD Pipelines
version: 0.0.1
grade: stable
base: core20
confinement: devmode

apps:
  cli:
    command: bin/cli
    plugs:
      - home
parts:
  cli:
    plugin: go
    source-type: local
    source: .

