name: datatourch-cli
summary: CLI for Datatouch 
description: |
      CLI for Datatouch Platform and CLI
version: git
grade: stable
base: core20

confinement: devmode

apps:
  woke:
    command: bin/dtl
    plugs:
      - home
parts:
  woke:
    plugin: go
    source-type: git
    source: https://github.com/datatorch/clients/cli 
