name: Go Tests
on:
  pull_request:
    paths:
      - 'clients/cli/**'
      - '**.go'
      - go.mod
      - go.sum

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: go mod download

      - name: Run all go tests
        run: go test -race ./...

      - name: Build
        run: go build -v ./clients/cli

  build-minimum:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        env:
          CGO_ENABLED: '0'
        run: go build -v ./clients/cli
