name: Go Lint
on:
  push:
    paths:
      - '**.go'
      - go.mod
      - go.sum
  pull_request:
    paths:
      - '**.go'
      - go.mod
      - go.sum

jobs:
  golangci:
    name: Golang Linting
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Check out code
        uses: actions/checkout@v2
      - name: Verify dependencies
        run: |
          go mod verify
          go mod download
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
