name: Javascript Lint

on:
  push:
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
      - '**/.eslint**'
  pull_request:
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
      - '**/.eslint**'

jobs:
  eslint:
    name: Javascript Linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Cache package dependencies
        uses: actions/cache@v2
        with:
          path: '**/.yarn/cache'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install modules
        run: yarn install

      - name: Run ESLint
        run: yarn run eslint --ext .tsx,.ts,.jsx,.js --max-warnings=0 --ignore-path .gitignore .
